-- Auto-generate a Markdown reference of the live keymaps.
-- Exposes the `:KeymapsDoc [path]` command (no default keybinding on purpose).
-- Output defaults to <config>/KEYMAPS.md; regenerate then `chezmoi re-add` to persist.
local M = {}

local mode_titles = {
	n = "Normal",
	i = "Insert",
	v = "Visual / Select",
	x = "Visual (charwise)",
	o = "Operator-pending",
	t = "Terminal",
}

-- What to show in the "Action" column: prefer a human description, then the rhs.
local function action_repr(m)
	if m.desc and m.desc ~= "" then
		return m.desc
	end
	if m.rhs and m.rhs ~= "" then
		return "`" .. m.rhs:gsub("%s+", " ") .. "`"
	end
	if m.callback then
		return "_lua callback_"
	end
	return ""
end

-- Keep user-facing mappings, drop plugin internals and Neovim builtin-default noise.
local function keep(m, leader)
	local lhs = m.lhs
	local desc = m.desc or ""
	local rhs = m.rhs or ""
	if lhs:match("^<Plug>") or lhs:match("^<SNR>") then
		return false
	end
	-- builtin default reminders (":help &-default", "...-default") and bare ex-command
	-- defaults (":next", ":cnext", ...) added by Neovim 0.11+
	if desc:match("%-default$") or desc:match("^:%a") then
		return false
	end
	local is_leader = leader ~= "" and lhs:sub(1, #leader) == leader
	-- plugin <Plug> glue with no description (keep it only if it's a leader binding)
	if rhs:match("^<Plug>") and desc == "" and not is_leader then
		return false
	end
	if desc ~= "" then
		return true
	end
	if is_leader then
		return true
	end
	-- special keys: <F5>, <C-h>, <S-Up>, <CR>, <Esc>, ...
	return lhs:match("^<") ~= nil
end

function M.generate(path)
	path = (path and path ~= "") and path or (vim.fn.stdpath("config") .. "/KEYMAPS.md")
	local leader = vim.g.mapleader or ""
	local leader_display = (leader == " " and "<Space>") or (leader == "" and "<unset>") or leader

	local lines = {
		"# Neovim keymaps",
		"",
		("> Auto-generated by `:KeymapsDoc` on %s — do not edit by hand."):format(os.date("%Y-%m-%d")),
		("> `<leader>` = `%s`, `timeoutlen` = %dms."):format(leader_display, vim.o.timeoutlen),
		"> Includes global maps plus buffer-local maps of the buffer it was run from,",
		"> so run it from a code buffer with your LSP attached to capture LSP mappings.",
		"",
	}

	for _, mode in ipairs({ "n", "i", "v", "x", "o", "t" }) do
		local rows, seen = {}, {}
		-- buffer-local first (LSP on_attach maps), then global; first occurrence wins
		for _, source in ipairs({ vim.api.nvim_buf_get_keymap(0, mode), vim.api.nvim_get_keymap(mode) }) do
			for _, m in ipairs(source) do
				if keep(m, leader) and not seen[m.lhs] then
					seen[m.lhs] = true
					rows[#rows + 1] = { lhs = m.lhs, action = action_repr(m) }
				end
			end
		end
		if #rows > 0 then
			table.sort(rows, function(a, b)
				return a.lhs:lower() < b.lhs:lower()
			end)
			lines[#lines + 1] = "## " .. (mode_titles[mode] or mode)
			lines[#lines + 1] = ""
			lines[#lines + 1] = "| Key | Action |"
			lines[#lines + 1] = "|-----|--------|"
			for _, r in ipairs(rows) do
				lines[#lines + 1] = ("| `%s` | %s |"):format(r.lhs:gsub("|", "\\|"), r.action:gsub("|", "\\|"))
			end
			lines[#lines + 1] = ""
		end
	end

	vim.fn.writefile(lines, path)
	return path
end

vim.api.nvim_create_user_command("KeymapsDoc", function(opts)
	local path = M.generate(opts.args)
	vim.notify("Keymaps written to " .. path)
end, { nargs = "?", complete = "file", desc = "Generate KEYMAPS.md from live keymaps" })

return M
