[tools]
awscli = "latest"
bat = "latest"
chezmoi = "latest"
atuin = "latest"
duckdb = "latest"
fd = "latest"
fzf = "latest"
gcloud = "latest"
gh = "latest"
go = "1.25"
golangci-lint = "v2.6.0"
java = "temurin-21"
jq = "latest"
k9s = "latest"
kubectl = "latest"
neovim = "latest"
node = "latest"
npm = "latest"
"npm:pyright" = "latest"
"npm:@vtsls/language-server" = "latest"
postgres = "latest"
python = "3.11"
redis = "latest"
rg = "latest"
stylua = "latest"
uv = "0.5.8"
