# show git branch in shell prompt (from: http://betterexplained.com/articles/aha-moments-when-learning-git/ and
# http://asemanfar.com/Current-Git-Branch-in-Bash-Prompt)
parse_git_branch()
{
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
export PS1="\[\033[00m\]\u@\h\[\033[01;34m\] \W \[\033[31m\]\$(parse_git_branch) \[\033[00m\]$\[\033[00m\] "

####
# to get colors in terminal (see: http://it.toolbox.com/blogs/lim/how-to-fix-colors-on-mac-osx-terminal-37214):
# enables coloring of your terminal:
export CLICOLOR=1
# specifies how to color specific items:
export LSCOLORS=GxFxCxDxBxegedabagaced

# source specific profile if provided
if [ -e "$HOME/.specific_profile" ]
then
  source "$HOME/.specific_profile"
fi

# bash shortcuts
alias pgstart='pg_ctl -D /usr/local/pgsql/data -l logfile start'
alias pgquit='pg_ctl -D /usr/local/pgsql/data stop -s -m fast'
alias ls='ls -F'

# source git completion script https://github.com/git/git/tree/master/contrib/completion
source ~/.git-completion.bash

# python env
export VIRTUALENV_DIR=$HOME/.virtualenv
export DEFAULT_VIRTUALENV='venv'
export CONDA_DIR=$HOME/.conda
python_init=$VIRTUALENV_DIR/$DEFAULT_VIRTUALENV/bin/activate
if [ -e $python_init ]
then
  source $python_init
fi

# ruby
eval "$(rbenv init -)"

# extend path
export PATH=/usr/local/Cellar:/usr/local/bin:/usr/local/sbin:$PATH
if [ -d $CONDA_DIR ]
then
  export PATH=$CONDA_DIR/bin:$PATH
fi
